//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    
    public partial class Product
    {
        public int BookID { get; set; }

        [Required(ErrorMessage = "this is required field")]
        public string BookName { get; set; }

        [Required(ErrorMessage = "this is required field")]
        public string Author { get; set; }

        [Required(ErrorMessage = "this is required field")]
        public string Image_1 { get; set; }

        [Required(ErrorMessage = "this is required field")]
        public string Image_2 { get; set; }

        [Required(ErrorMessage = "this is required field")]
        public string Image_3 { get; set; }

        [Required(ErrorMessage = "this is required field")]
        public string Image_4 { get; set; }

        [Required(ErrorMessage = "this is required field")]
        public double Price { get; set; }

        [Required(ErrorMessage = "this is required field")]
        public int PrintLength { get; set; }

        [Required(ErrorMessage = "this is required field")]
        public string Language { get; set; }

        [Required(ErrorMessage = "this is required field")]
        public System.DateTime PublicationDate { get; set; }

        [Required(ErrorMessage = "this is required field")]
        public string Publisher { get; set; }

        [Required(ErrorMessage = "this is required field")]
        public string Description { get; set; }
        public HttpPostedFileBase ImageFile1 { get; set; }
        public HttpPostedFileBase ImageFile2 { get; set; }
        public HttpPostedFileBase ImageFile3 { get; set; }
        public HttpPostedFileBase ImageFile4 { get; set; }


    }
}
